name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Render Deployment
        run: |
          curl -X POST -d '' "https://api.render.com/deploy/srv-csugdaqlqhvc73cmlq30?key=h_khFN5s91o"
  
          